### ISSUE TITLE
go.mod

### ISSUE THREAD

**Issue by 89z** [chmike/cmac-go#4]
Good morning,

can you please add go.mod file? Thank you

**Comment by chmike** [comment]
Done, I have also tagged it as v1.0.0 so that it's a stable release.
Thank you for your interest in this package.

**Comment by 89z** [comment]
oh thats great! Hm, now I have to decide what package to use :)

right now I am using this one:

https://github.com/dchest/cmac

do you know if yours is better?

**Comment by 89z** [comment]
Ah, I see, the signature is simpler:

https://github.com/chmike/cmac-go/blob/6399ef0947ca28fa720d00a95d125823cf0cf3e6/cmac_test.go#L15-L18

I think I like this one here :)

**Comment by chmike** [comment]
I would first check if we get the same result with both. This would be a simple validity check. 
I provide an `Equal` function that doesn't leak timing information. He doesn't seam to provide one. 
There might by one in Crypto. I didn't check. 

You could also do a benchmark comparison. I wouldn't expect much difference.

I have a few typos left in the function/method comments, and Sum is lacking a comment. But this doesn't alter the functioning.

**Comment by 89z** [comment]
Other package is also using `crypto/subtle`:

~~~go
v1 := shift1(d.k1, d.k1)
d.k1[n-1] ^= byte(subtle.ConstantTimeSelect(v1, r, 0))

v2 := shift1(d.k1, d.k2)
d.k2[n-1] ^= byte(subtle.ConstantTimeSelect(v2, r, 0))
~~~

but personally I don't need the extra security.

https://github.com/dchest/cmac/blob/c7fe9847/cmac.go#L53-L57

**Comment by chmike** [comment]
This looks like a significant difference between the two code that should be investigated. 
It may yield a performance difference. 

With a quick look, I could not see the reason to use this ConstantTimeSelect. I may check this week-end.

**Comment by chmike** [comment]
I see this possible simplification in my  `shiftLeftOneBit` function: 

```
overflow = (tmp >> 7) & 1
```
can be changed into 

```
overflow = tmp >> 7
``` 
The compiler may have already done it. 

This `if` statements 

```
if tmp&0x80 == 0x80 {
	cm.k1[bs-1] ^= 0x87
}
```

can be replaced by this constant time expression yielding the same result:

```
cm.k1[bs-1] ^= (int8(tmp)>>7)&0x87
```

Both code would be as safe.

**Comment by 89z** [comment]
I think the main interest to me is the function signature. Yours is similar to `crypto/hmac`, I like that

**Comment by 89z** [comment]
Oh, that's bad. Can you please let me know when its fixed? I want to use your package, but it needs to actually work hehe

**Comment by chmike** [comment]
It works for a single write. I'll let you know. Thanks.

**Comment by chmike** [comment]
I have updated the code and release version v1.1.0. This is the one you should use. 
The release v1.0.0 will be removed as invalid.

**Comment by 89z** [comment]
OK, thanks for everything!

**Comment by chmike** [comment]
Thank you for choosing my package. I wish you enjoy it.

**Comment by 89z** [comment]
Also, you should add a link to documentation, one of these:

https://godocs.io/github.com/chmike/cmac-go
https://pkg.go.dev/github.com/chmike/cmac-go

**Comment by chmike** [comment]
You are right. It's done. I added shields and extended tests to get 100% coverage.
